// <auto-generated />
namespace JobSearch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcompanyandsalaryinjobApplications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcompanyandsalaryinjobApplications));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071809303_added company and salary in jobApplications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
